# Define a custom collection called "blogs"
collections:
  blogs:
    output: true                # true = generate a real web page for each blog
    permalink: /blogs/:path/    # Keep the folder structure in the URL